### ISSUE TITLE
Unit test issues in IntelliJ - follow-up to #2934

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/Terasology#2951]
After merging #2934 a handful of unit tests are showing strange errors in IntelliJ, while working fine in Jenkins (via Gradle) and probably also fine in Eclipse?

Possibly of interest to @oniatus @vampcat @SkySom @kaen @iaronaraujo

See #2934 for further details.

**Comment by vampcat** [comment]
For the record, the unit tests run fine in my IntelliJ workspace.

**Comment by oniatus** [comment]
Found no way to reproduce the exception from https://github.com/MovingBlocks/Terasology/pull/2942#issuecomment-301664443 in my Eclipse workspace. Weird that this behaves so different  :confused:

**Comment by gianluca-nitti** [comment]
I had problems too when I pulled the upstream to my fork and to my local repository yesterday, IntelliJ was showing compilation errors (don't remember exactly where). I did the following:
- Close IntelliJ
- Run the tests from Gradle: `gradlew test`; I saw it downloaded some jars during the process, so I suppose the problem was IntelliJ not finding these dependencies; took a while, but all the tests passed
- Update the workspace with `gradlew idea` (not sure it is actually necessary)
- When I restarted the IDE, I saw no more compilation errors, and I was able to run both the tests from within IntelliJ and start the engine using the appropriate run configurations.

**Comment by Cervator** [comment]
I thought maybe I had to do a thorough workspace cleanup and recompile, but so far no luck. Tried the `gradlew test` but it runs into problems with a few of my modules for unrelated reasons (and `gradlew :engine-tests:test` is bizarrely slow - known issue)

Probably I should tidy up to where my workspace is more solid and try again. I did notice `gradlew test` started grabbing a few more dependencies which is odd, even if it didn't help yet. Maybe some stuff is indeed not getting picked up by IntelliJ.

**Comment by Cervator** [comment]
Update: Still no luck. Have tried a full `gradlew clean cleanIdea idea` after disabling a few problematic modules. Have tried the various dependency ordering and exclusion ideas from the links in the original issue. Have tried `gradlew test` both with the full exclusion setup and with the code as-is.

I *suspect* it relates to either IntelliJ version (my main IntelliJ is on 2016.3.3 so a little old) or the presence of certain modules using certain types of tests that end up causing a conflict between their test source set and `engine-tests` - I've seen that before and it outright screws up the test setup as not all of them are even visible. That in turn may relate to how modules register with `gestalt-module` within environment-based unit tests?

```
22:56:19.603 [Test worker] ERROR org.terasology.module.TableModuleRegistry - Module Pathfinding-0.2.0-SNAPSHOT already registered from [C:\Dev\Terasology\Git\Terasology\modules\Pathfinding], cannot register same module from [C:\Dev\Terasology\Git\Terasology\engine-tests\build\libs\engine-tests-1.4.1-SNAPSHOT.jar]
```

Would be curious if somebody with Pathfinding or NameGenerator could succeed with `gradlew test` - both of those have failing tests in Jenkins from a different issue.

I've had some musings about rearranging how `engine-tests` is set up, as we do not necessarily need it split out anymore - once upon a time the split was done because of a dependency ordering/resolution issue. Something like modules depending on a unified engine/engine-tests would not be able to do a *compile* dependency on the engine's test source set to then later base their own tests on. But since those days Gradle has added more granular source set definitions as has IntelliJ (maybe Eclipse is OK too?)

Alternatively maybe my overall Gradle rework will shake something loose ... will keep an eye out on this one :-)

**Comment by Cervator** [comment]
Can no longer reproduce - closing!
